# kaolin
# theme create by: https://github.com/AnshumanNeon
# update by(sort by time):
# thanks for all contributor!!

# if you want to make border display just set it same as sidebar background color

# code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-macchiato"

# ========= border =========
file_panel_border = "#74b09a"
sidebar_border = "#17171a"
footer_border = "#74b09a"

# ========= border active =========
file_panel_border_active = "#74b09a"
sidebar_border_active = "#57b2c2"
footer_border_active = "#57b2c2"
modal_border_active = "#868686"

# ========= background (bg) =========
full_screen_bg = "#17171a"
file_panel_bg = "#17171a"
sidebar_bg = "#17171a"
footer_bg = "#17171a"
modal_bg = "#17171a"

# ========= foreground (fg) =========
full_screen_fg = "#efefef"
file_panel_fg = "#efefef"
sidebar_fg = "#efefef"
footer_fg = "#efefef"
modal_fg = "#efefef"

# ========= special color =========
cursor = "#f5c791"
correct = "#74b09a"
error = "#c74a4d"
hint = "#4fa8a3"
cancel = "#d7936d"
# gradient color can only have two color!
gradient_color = ["#74b09a", "#c74a4d"]

# ========= file panel special items =========
file_panel_top_directory_icon = "#f5c791"
file_panel_top_path = "#d7936d"
file_panel_item_selected_fg = "#4fa8a3"
file_panel_item_selected_bg = "#17171a"

# ========= sidebar special items =========
sidebar_title = "#f5c791"
sidebar_item_selected_fg = "#ba667d"
sidebar_item_selected_bg = "#17171a"
sidebar_divider = "#868686"

# ========= modal special items =========
modal_cancel_fg = "#eedcc1"
modal_cancel_bg = "#c74a4d"

modal_confirm_fg = "#eedcc1"
modal_confirm_bg = "#3e594a"

# ========= help menu =========
help_menu_hotkey = "#4fa8a3"
help_menu_title = "#f5c791"