# onedark
# theme create by: https://github.com/CommandJoo
# update by(sort by time):
# thanks for all contributor!!

# if you want to make sidebar border display just set it same as sidebar background color

# code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "onedark"

# ========= border =========
file_panel_border = "#737994" # overlay0
sidebar_border = "#737994" # base
footer_border = "#737994" # overlay0

# ========= border active =========
file_panel_border_active = "#57A5E5" # lavendar
sidebar_border_active = "#DE5D68" # red
footer_border_active = "#8FB573" # green
modal_border_active = "#51A8B3" # overlay2

# ========= background (bg) =========
full_screen_bg = "#2C2D31" # base
file_panel_bg = "#232326" # base
sidebar_bg = "#232326" # base
footer_bg = "#232326" # base
modal_bg = "#35363B" # base

# ========= foreground (fg) =========
full_screen_fg = "#A7AAB0" # subtext0
file_panel_fg = "#A7AAB0" # subtext0
sidebar_fg = "#A7AAB0" # subtext0
footer_fg = "#A7AAB0" # subtext0
modal_fg = "#A7AAB0" # subtext0

# ========= special color =========
cursor = "#68AEE8" # rosewater
correct = "#a6d189" # green
error = "#DE5D68" # red
hint = "#68AEE8" # sapphire
cancel = "#C49060" # maroon
# gradient color can only have two color!
gradient_color = ["#68AEE8", "#BB70D2"] # [blue, mauve]

# ========= file panel special items =========
file_panel_top_directory_icon = "#DBB671" # green
file_panel_top_path = "#DBB671" # blue
file_panel_item_selected_fg = "#51A8B3" # sky
file_panel_item_selected_bg = "#2C2D31" # base

# ========= sidebar special items =========
sidebar_title = "#57A5E5" # sapphire
sidebar_item_selected_fg = "#51A8B3" # sky
sidebar_item_selected_bg = "#2C2D31" # base
sidebar_divider = "#818387" # overlay2

# ========= modal special items =========
modal_cancel_fg = "#414559" # surface0
modal_cancel_bg = "#DE5D68" # maroon

modal_confirm_fg = "#414559" # surface0
modal_confirm_bg = "#51A8B3" # sky

# ========= help menu =========
help_menu_hotkey = "#51A8B3" # sky
help_menu_title = "#BB70D2" # maroon
