# tokyonight
# theme create by: https://github.com/pearcidar
# update by(sort by time):
# thanks for all contributor!!

# if you want to make border display just set it same as sidebar background color

# code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-macchiato"

# ========= border =========
file_panel_border = "#414868"
sidebar_border = "#24283b"
footer_border = "#414868"

# ========= border active =========
file_panel_border_active = "#b4befe"
sidebar_border_active = "#f7768e"
footer_border_active = "#73daca"
modal_border_active = "#73daca"

# ========= background (bg) =========
full_screen_bg = "#1a1b26"
file_panel_bg = "#1a1b26"
sidebar_bg = "#1a1b26"
footer_bg = "#1a1b26"
modal_bg = "#1a1b26"

# ========= foreground (fg) =========
full_screen_fg = "#a9b1d6"
file_panel_fg = "#a9b1d6"
sidebar_fg = "#a9b1d6"
footer_fg = "#a9b1d6"
modal_fg = "#a9b1d6"

# ========= special color =========
cursor = "#ff9e64"
correct = "#9ece6a"
error = "#f7768e"
hint = "#7dcfff"
cancel = "#ff9e64"
# gradient color can only have two color!
gradient_color = ["#7aa2f7", "#bb9af7"]

# ========= file panel special items =========
file_panel_top_directory_icon = "#73daca"
file_panel_top_path = "#7aa2f7"
file_panel_item_selected_fg = "#2ac3de"
file_panel_item_selected_bg = "#1a1b26"

# ========= sidebar special items =========
sidebar_title = "#73daca"
sidebar_item_selected_fg = "#7dcfff"
sidebar_item_selected_bg = "#1a1b26"
sidebar_divider = "#565f89"

# ========= modal special items =========
modal_cancel_fg = "#24383b"
modal_cancel_bg = "#e0af68"

modal_confirm_fg = "#24283b"
modal_confirm_bg = "#9ece6a"

# ========= help menu =========
help_menu_hotkey = "#7dcfff"
help_menu_title = "#73daca"
