-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x0A55",
  mode = "2560x1440@240.00",
  position = "0x240",
  scale = 1.6,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAGEAR 0x00002D91",
  mode = "1920x1080@144.00",
  position = "1600x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "9", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "10", monitor = "desc:BOE 0x0A55", persistent = true })
hl.workspace_rule({ workspace = "11", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "12", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "13", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "14", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "15", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "16", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "17", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "18", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "19", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
hl.workspace_rule({ workspace = "20", monitor = "desc:LG Electronics LG ULTRAGEAR 0x00002D91", persistent = true })
