# style name or json path (default "auto")
style: "/home/isaac/.config/glow/mono.json"
# mouse support (tui-mode only)
mouse: false
# use pager to display markdown
pager: false
# word-wrap at width
width: 80
# show all files, including hidden and ignored.
all: true
