# the current version of the config schema
version: 1
# what protocol to use when performing git operations. supported values: ssh, https
git_protocol: https
# what editor gh should run when creating issues, pull requests, etc. if blank, will refer to environment.
editor:
# when to interactively prompt. this is a global config that cannot be overridden by hostname. supported values: enabled, disabled
prompt: enabled
# preference for editor-based interactive prompting. this is a global config that cannot be overridden by hostname. supported values: enabled, disabled
prefer_editor_prompt: disabled
# a pager program to send command output to, e.g. "less". if blank, will refer to environment. set the value to "cat" to disable the pager.
pager:
# aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
# the path to a unix socket through which to send http connections. if blank, http traffic will be handled by net/http.defaulttransport.
http_unix_socket:
# what web browser gh should use when opening urls. if blank, will refer to environment.
browser:
# whether to display labels using their rgb hex color codes in terminals that support truecolor. supported values: enabled, disabled
color_labels: disabled
# whether customizable, 4-bit accessible colors should be used. supported values: enabled, disabled
accessible_colors: disabled
# whether an accessible prompter should be used. supported values: enabled, disabled
accessible_prompter: disabled
# whether to use an animated spinner as a progress indicator. if disabled, a textual progress indicator is used instead. supported values: enabled, disabled
spinner: enabled
